---

 - name: adding credentials to root account
   lineinfile: create=yes dest=/root/.boto insertafter=EOF line="{{ item }}" owner=root group=root
   with_items:
   - '[Credentials]'
   - 'aws_access_key_id="{{ aws_key}}"'
   - 'aws_secret_access_key="{{ aws_secret }}"'

 - name: 'Run bot'
   shell: 'python /home/ubuntu/crabot/bot/main.py &'

 - name: 'Changing permissions'
   file: path=/home/ubuntu/crabot/bot/main.py owner=root mode=7777

 - name: 'Cd and run'
   script: /home/ubuntu/crabot/bot/main.py
   become: true
   become_user: root

 - name: 'apt update'
   apt:
     upgrade: dist

 - name: 'apt upgrade'
   apt:
     update-cache: yes
