---

 - name: adding credentials to root account
   lineinfile: create=yes dest=/root/.boto insertafter=EOF line="{{ item }}" owner=root group=root
   with_items:
   - '[Credentials]'
   - 'aws_access_key_id="{{ aws_key }}"'
   - 'aws_secret_access_key="{{ aws_secret }}"'

# - name: remove nohup
#   sudo: true
#   shell: rm /home/ubuntu/crabot/bot/nohup.out
 #- name: Create a py file
#   shell: echo "print 'hello'" > hello.py ; python hello.py

# - name: Install node
#   sudo: true
#   apt: name=nodejs-legacy state=present update_cache=true

# - name: Install forever
#   sudo: true
#   npm: name=forever global=yes state=present

 - name: run python
   sudo: true
   shell: echo "#!/bin/bash\nwhile [1]; do python main.py; done" > /home/ubuntu/crabot/bot/a.sh ; chmod u+x /home/ubuntu/crabot/bot/a.sh ; /home/ubuntu/crabot/bot/a.sh
#   shell: forever start -c python /home/ubuntu/crabot/bot/main.py



# - name: Run crabot
#   sudo: true
#   shell: cd /home/ubuntu/crabot/bot ; python main.py


# - name: 'apt update'
#   apt:
#     upgrade: dist

# - name: 'apt upgrade'
#   apt:
#     update-cache: yes
