---
 - hosts: localhost
   connection: local
   gather_facts: False
   vars:
    keypair: se_hw5
    instance_type: t2.micro
    security_group: ec2
    image: ami-09e27439
    region: us-west-2
   tasks:
     - name: Creating EC2 instance
       ec2:
        keypair: "{{keypair}}"
        group: "{{security_group}}"
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        region: "{{region}}"
        wait: true
        count: 1
        instance_tags:
         Name: ec2
       register: ec2
     - name: add the instance to a group called launched
       add_host: hostname={{ec2.instances[0].public_ip }} groups=launched
       with_items: '{{ec2.instances}}'
     - name: wait for SSH
       wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
       with_items: '{{ec2.instances}}'



 - hosts: launched
   remote_user: ubuntu
   sudo: yes
   roles:
     - role: common
   vars:
     aws_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
     aws_secret: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
