---
 - hosts: localhost
   connection: local
   gather_facts: False
   vars:
    keypair: se_hw5
    instance_type: t2.micro
    security_group: crabot
    image: ami-85e24ce5
    region: us-west-2
   tasks:
     - name: Creating EC2 instance
       ec2:
        keypair: "{{keypair}}"
        group: "{{security_group}}"
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        region: "{{region}}"
        wait: true
        count: 1
        instance_tags:
         Name: ec2_crabot
       register: ec2_crabot
     - name: add the instance to a group called launched
       add_host: hostname={{ ec2_crabot.instances[0].public_ip }} groups=launched


     - name: wait for SSH
       wait_for: host={{ ec2_crabot.instances[0].public_dns_name }} port=22 delay=60 timeout=320 state=started

     - name: Curl subscribe to PR
       shell: curl -u "chethan1801:chethan123" -i https://api.github.com/hub -F "hub.mode=subscribe" -F "hub.topic=https://github.com/chethan1801/TestRepo/events/pull_request" -F "hub.callback=http://{{ ec2_crabot.instances[0].public_ip }}:5000/chethan1801/TestRepo/pull_request"

     - name: Curl subscribe to PR Comment
       shell: curl -u "chethan1801:chethan123" -i https://api.github.com/hub -F "hub.mode=subscribe" -F "hub.topic=https://github.com/chethan1801/TestRepo/events/issue_comment" -F "hub.callback=http://{{ ec2_crabot.instances[0].public_ip }}:5000/chethan1801/TestRepo/issue_comment"

     - name: Curl subscribe to Commit comment
       shell: curl -u "chethan1801:chethan123" -i https://api.github.com/hub -F "hub.mode=subscribe" -F "hub.topic=https://github.com/chethan1801/TestRepo/events/commit_comment" -F "hub.callback=http://{{ ec2_crabot.instances[0].public_ip }}:5000/chethan1801/TestRepo/commit_comment"





 - hosts: launched
   remote_user: ubuntu
   sudo: yes
   roles:
     - role: common
   vars:
     aws_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
     aws_secret: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
